version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'php artisan serve --host=0.0.0.0 && php artisan migrate'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
      MYSQL_ROOT: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
